[project]
name = "cell-eval"
version = "0.7.2"
description = "Evaluation metrics for single-cell perturbation predictions"
readme = "README.md"
authors = [
    { name = "Noam Teyssier", email = "noam.teyssier@arcinstitute.org" },
    { name = "Abhinav Adduri", email = "abhinav.adduri@arcinstitute.org" },
    { name = "Yusuf Roohani", email = "yusuf.roohani@arcinstitute.org" },
]
requires-python = ">=3.11"
dependencies = [
    "networkit>=11.2",
    "pdex>=0.2.2",
    "polars>=1.30.0",
    "pyyaml>=6.0.2",
    "scanpy>=1.10.3",
    "pyarrow>=18.0.0",
    "tqdm>=4.67.1",
    "anndata>=0.12.10",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "prek>=0.4.3",
    "pytest>=8.3.5",
    "ty>=0.0.19",
]

[project.scripts]
cell-eval = "cell_eval.__main__:main"
